#pragma once
//Do not edit this file with out editing client version of this file as well.
//They need to be consistant to allow for proper communication
#include "RakPeerInterface.h"
#include "MessageIdentifiers.h"

enum GamePacketID : unsigned char{
	ID_SPAWN_ENTITY = ID_USER_PACKET_ENUM + 1,	//packet enum for spawning an entity
};
