#pragma once
//Do not edit this file with out editing client version of this file as well.
//They need to be consistant to allow for proper communication

#include "RakPeerInterface.h"
#include "MessageIdentifiers.h"

enum GamePacketID {
	ID_PLAYER_POS = ID_USER_PACKET_ENUM + 1,	//defines the first enum value to not conflict with network engine
	ID_CLIENT_NET_ID							//packet that gives net id for client
};
