#pragma once
//Do not edit this file with out editing client version of this file as well.
//They need to be consistant to allow for proper communication

#include "RakPeerInterface.h"
#include "MessageIdentifiers.h"

enum GamePacketID {
	ID_NEW_PLAYER_CONNECTED = ID_USER_PACKET_ENUM + 1, //defines the first enum value to not conflict with network engine
	ID_PLAYER_INFO,
	ID_GAME_MESSAGE,
	ID_ENTITY_POS
};
