#pragma once
//Do not edit this file with out editing server version of this file as well.
//They need to be consistant to allow for proper communication

#include "RakPeerInterface.h"
#include "MessageIdentifiers.h"

namespace Network {
	enum GamePacketID {
		ID_SPAWN_PLAYER = ID_USER_PACKET_ENUM + 1, //defines the first enum value to not conflict with network engine
		ID_PLAYER_POS,

	};
}