#ifndef PREAMBLE_GLSL
#define PREAMBLE_GLSL

#define POSITION_ATTRIB_LOCATION 0
#define TEXCOORD_ATTRIB_LOCATION 1
#define NORMAL_ATTRIB_LOCATION 2
#define COLOR_ATTRIB_LOCATION 3

#define MAT3_ATTRIB_LOCATION 4

#define MAT4_ATTRIB_LOCATION 7

#endif

